version: 2

project_name: omada-exporter

builds:
  - id: omada_exporter
    main: .
    binary: omada-exporter
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X github.com/RCooLeR/omada_exporter/cmd.version={{ .Version }}

archives:
  - formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md

checksum:
  name_template: "checksums.txt"

release:
  github:
    owner: RCooLeR
    name: omada_exporter
  draft: false

dockers_v2:
  - id: omada_exporter
    ids:
      - omada_exporter
    dockerfile: Dockerfile.goreleaser
    images:
      - rcooler/omada_exporter
      - rcooler/omada-exporter
    tags:
      - "{{ .Version }}"
      - latest
    platforms:
      - linux/amd64
